### PR TITLE
Transpiler, Allocations dataframe

### PR DESCRIPTION
**Pull request by jamesfulford**
Code that writes code.

Flow:
- Inform data fetcher of data needed (tickers and dates) (we have tools to help, but the transpiler does not do this)
- Fetch historical / Synthesize ETF / Simulate future price data (`closes` dataframe should be passed to this code)
- [transpiled output] Compute indicators
- [transpiled output] Populate allocations dataframe
- [transpiled output] Track branch usage
- Rudimentary reports

Next steps:
- Provide rebalance logic to vectorbt
- Execute backtest
- Report results
- Analyze branch usage
- Tweak parameters based on results and run again (optimizing)

TODO:
- [x] Implement more indicators in precompute_indicator

# Example output
Symphony input: https://app.composer.trade/symphony/2XE43Kcoqa0uLSOBuN3q/details

## Report output
```
Start: 2011-10-18 00:00:00
End: 2022-10-25 00:00:00 (2774 trading days)

Checking for days that are not 100% allocated...
All days are 100% allocated.

Allocations by ticker (allocation% * days%)
  TQQQ  48.4%
  UVXY  22.7%
  SQQQ  18.3%
  TLT    4.5%
  SOXL   3.9%
  SOXS   1.5%
  TECL   0.6%
  UPRO   0.1%


Days each branch was activated (all branches may total > 100%)
44.3% (1230 of 2774) Close(SPY) > SMA(SPY, 200d) AND (not RSI(TQQQ, 10d) > 79) AND (not RSI(SPXL, 10d) > 80) AND (not CumulativeReturn(TQQQ, 5d) > 20)
34.0% ( 944 of 2774) Close(SPY) > SMA(SPY, 200d) AND (not RSI(TQQQ, 10d) > 79) AND (not RSI(SPXL, 10d) > 80) AND CumulativeReturn(TQQQ, 5d) > 20 AND (not RSI(TQQQ, 10d) < 31)
 7.5% ( 207 of 2774) (not Close(SPY) > SMA(SPY, 200d)) AND (not RSI(TQQQ, 10d) < 31) AND (not RSI(SPY, 10d) < 30) AND Close(TQQQ) < SMA(TQQQ, 20d) AND (not CumulativeReturn(SQQQ, 10d) > 23)
 5.2% ( 143 of 2774) (not Close(SPY) > SMA(SPY, 200d)) AND (not RSI(TQQQ, 10d) < 31) AND (not RSI(SPY, 10d) < 30) AND (not Close(TQQQ) < SMA(TQQQ, 20d)) AND (not RSI(SQQQ, 10d) < 31)
 4.0% ( 110 of 2774) Close(SPY) > SMA(SPY, 200d) AND RSI(TQQQ, 10d) > 79
 2.6% (  72 of 2774) (not Close(SPY) > SMA(SPY, 200d)) AND RSI(TQQQ, 10d) < 31
 1.0% (  29 of 2774) Close(SPY) > SMA(SPY, 200d) AND (not RSI(TQQQ, 10d) > 79) AND RSI(SPXL, 10d) > 80
 0.9% (  24 of 2774) Close(SPY) > SMA(SPY, 200d) AND (not RSI(TQQQ, 10d) > 79) AND (not RSI(SPXL, 10d) > 80) AND CumulativeReturn(TQQQ, 5d) > 20 AND RSI(TQQQ, 10d) < 31
 0.4% (  11 of 2774) (not Close(SPY) > SMA(SPY, 200d)) AND (not RSI(TQQQ, 10d) < 31) AND (not RSI(SPY, 10d) < 30) AND (not Close(TQQQ) < SMA(TQQQ, 20d)) AND RSI(SQQQ, 10d) < 31
 0.1% (   4 of 2774) (not Close(SPY) > SMA(SPY, 200d)) AND (not RSI(TQQQ, 10d) < 31) AND RSI(SPY, 10d) < 30
 0.0% (   0 of 2774) (not Close(SPY) > SMA(SPY, 200d)) AND (not RSI(TQQQ, 10d) < 31) AND (not RSI(SPY, 10d) < 30) AND Close(TQQQ) < SMA(TQQQ, 20d) AND CumulativeReturn(SQQQ, 10d) > 23
```

## Compiler Output

```python
def build_allocations_matrix(closes):
    indicators = pd.DataFrame(index=closes.index)

    indicators['SMA(SPY, 200d)'] = precompute_indicator(closes['SPY'], ':moving-average-price', 200)
    indicators['RSI(TQQQ, 10d)'] = precompute_indicator(closes['TQQQ'], ':relative-strength-index', 10)
    indicators['RSI(SPXL, 10d)'] = precompute_indicator(closes['SPXL'], ':relative-strength-index', 10)
    indicators['CumulativeReturn(TQQQ, 5d)'] = precompute_indicator(closes['TQQQ'], ':cumulative-return', 5)
    indicators['RSI(TQQQ, 10d)'] = precompute_indicator(closes['TQQQ'], ':relative-strength-index', 10)
    indicators['RSI(UVXY, 10d)'] = precompute_indicator(closes['UVXY'], ':relative-strength-index', 10)
    indicators['RSI(SQQQ, 10d)'] = precompute_indicator(closes['SQQQ'], ':relative-strength-index', 10)
    indicators['RSI(TQQQ, 10d)'] = precompute_indicator(closes['TQQQ'], ':relative-strength-index', 10)
    indicators['RSI(SPY, 10d)'] = precompute_indicator(closes['SPY'], ':relative-strength-index', 10)
    indicators['SMA(TQQQ, 20d)'] = precompute_indicator(closes['TQQQ'], ':moving-average-price', 20)
    indicators['CumulativeReturn(SQQQ, 10d)'] = precompute_indicator(closes['SQQQ'], ':cumulative-return', 10)
    indicators['RSI(SQQQ, 10d)'] = precompute_indicator(closes['SQQQ'], ':relative-strength-index', 10)
    indicators['RSI(TLT, 10d)'] = precompute_indicator(closes['TLT'], ':relative-strength-index', 10)
    indicators['RSI(SOXS, 10d)'] = precompute_indicator(closes['SOXS'], ':relative-strength-index', 10)
    indicators['RSI(TLT, 10d)'] = precompute_indicator(closes['TLT'], ':relative-strength-index', 10)
    indicators['RSI(SQQQ, 10d)'] = precompute_indicator(closes['SQQQ'], ':relative-strength-index', 10)
    indicators['RSI(TQQQ, 10d)'] = precompute_indicator(closes['TQQQ'], ':relative-strength-index', 10)
    indicators['RSI(SOXL, 10d)'] = precompute_indicator(closes['SOXL'], ':relative-strength-index', 10)

    # If any indicator is not available, we cannot compute that day
    # (assumes all na's stop at some point and then are continuously available into the future, no skips)
    indicators.dropna(axis=0, inplace=True)
    

    #
    # Algorithm Logic and instrumentation
    #
    allocations = pd.DataFrame(index=indicators.index, columns=closes.columns).fillna(0)

    # Track branch usage based on :id of "leaf" condition (closest :if-child up the tree to that leaf node)
    branch_tracker = pd.DataFrame(index=indicators.index, columns=['151b8783-383a-4aba-85ba-fcea5d1293a0', '5873b8cd-fa33-4d13-87f4-b41470b281e9', '865d1809-45a9-4517-b189-2e065cf2dc80', '8c96da44-2efa-40bd-ba37-e7ea6719fb11', '9e194caa-d8d6-49ab-afe7-174291e2db7c', 'a4405ff4-7527-45dc-a20d-89335e04fa25', 'b3008001-2da1-4c3c-8d73-b6b878cf05d7', 'c542cf1f-7fd1-474b-8a9c-e5bbd76aed68', 'd804b71b-d96f-4fbc-9fff-6c7bd54d7c62', 'e7fca8be-a7bc-4e4b-a01e-a95cc33df202', 'ff951ad9-d2f1-48a8-a33d-995d9061fd19']).fillna(0)

    for row in indicators.index:
    
        if closes.at[row, 'SPY'] > indicators.at[row, 'SMA(SPY, 200d)']:
            if indicators.at[row, 'RSI(TQQQ, 10d)'] > 79:
                branch_tracker.at[row, '5873b8cd-fa33-4d13-87f4-b41470b281e9'] = 1
                allocations.at[row, 'UVXY'] += 1.0
            else:
                if indicators.at[row, 'RSI(SPXL, 10d)'] > 80:
                    branch_tracker.at[row, '151b8783-383a-4aba-85ba-fcea5d1293a0'] = 1
                    allocations.at[row, 'UVXY'] += 1.0
                else:
                    if indicators.at[row, 'CumulativeReturn(TQQQ, 5d)'] > 20:
                        if indicators.at[row, 'RSI(TQQQ, 10d)'] < 31:
                            branch_tracker.at[row, 'b3008001-2da1-4c3c-8d73-b6b878cf05d7'] = 1
                            allocations.at[row, 'TQQQ'] += 1.0
                        else:
                            branch_tracker.at[row, 'ff951ad9-d2f1-48a8-a33d-995d9061fd19'] = 1
                            for _sort_value, ticker in sorted([
                                (indicators.at[row, 'RSI(UVXY, 10d)'], 'UVXY'),
                                (indicators.at[row, 'RSI(SQQQ, 10d)'], 'SQQQ'),
                            ], reverse=True)[1:]:  # :top 1
                                allocations.at[row, ticker] += 1.0
                    else:
                        branch_tracker.at[row, 'a4405ff4-7527-45dc-a20d-89335e04fa25'] = 1
                        allocations.at[row, 'TQQQ'] += 1.0
        else:
            if indicators.at[row, 'RSI(TQQQ, 10d)'] < 31:
                # Tech
                branch_tracker.at[row, '865d1809-45a9-4517-b189-2e065cf2dc80'] = 1
                allocations.at[row, 'TECL'] += 0.25
                branch_tracker.at[row, '865d1809-45a9-4517-b189-2e065cf2dc80'] = 1
                allocations.at[row, 'TQQQ'] += 0.25
                branch_tracker.at[row, '865d1809-45a9-4517-b189-2e065cf2dc80'] = 1
                allocations.at[row, 'SOXL'] += 0.5
            else:
                if indicators.at[row, 'RSI(SPY, 10d)'] < 30:
                    branch_tracker.at[row, '8c96da44-2efa-40bd-ba37-e7ea6719fb11'] = 1
                    allocations.at[row, 'UPRO'] += 1.0
                else:
                    if closes.at[row, 'TQQQ'] < indicators.at[row, 'SMA(TQQQ, 20d)']:
                        if indicators.at[row, 'CumulativeReturn(SQQQ, 10d)'] > 23:
                            branch_tracker.at[row, 'd804b71b-d96f-4fbc-9fff-6c7bd54d7c62'] = 1
                            allocations.at[row, 'TQQQ'] += 1.0
                        else:
                            branch_tracker.at[row, '9e194caa-d8d6-49ab-afe7-174291e2db7c'] = 1
                            for _sort_value, ticker in sorted([
                                (indicators.at[row, 'RSI(SQQQ, 10d)'], 'SQQQ'),
                                (indicators.at[row, 'RSI(TLT, 10d)'], 'TLT'),
                            ], reverse=True)[1:]:  # :top 1
                                allocations.at[row, ticker] += 0.5
                            branch_tracker.at[row, '9e194caa-d8d6-49ab-afe7-174291e2db7c'] = 1
                            for _sort_value, ticker in sorted([
                                (indicators.at[row, 'RSI(SOXS, 10d)'], 'SOXS'),
                                (indicators.at[row, 'RSI(TLT, 10d)'], 'TLT'),
                            ], reverse=True)[1:]:  # :top 1
                                allocations.at[row, ticker] += 0.5
                    else:
                        if indicators.at[row, 'RSI(SQQQ, 10d)'] < 31:
                            branch_tracker.at[row, 'e7fca8be-a7bc-4e4b-a01e-a95cc33df202'] = 1
                            allocations.at[row, 'SQQQ'] += 1.0
                        else:
                            branch_tracker.at[row, 'c542cf1f-7fd1-474b-8a9c-e5bbd76aed68'] = 1
                            for _sort_value, ticker in sorted([
                                (indicators.at[row, 'RSI(TQQQ, 10d)'], 'TQQQ'),
                                (indicators.at[row, 'RSI(SOXL, 10d)'], 'SOXL'),
                            ], reverse=False)[1:]:  # :bottom 1
                                allocations.at[row, ticker] += 1.0

    return allocations, branch_tracker
```

### CODE REVIEW

**Comment by androslee** [comment]
we need to start defining what the data requirements are going to be for the later half
1. bool parameter so we know if data lookup is needed (easy)
2. endpoints to get data from (yahoo.....idk whoelse)
3. stocks to get data for (from the transpiler digestion)
4. time granularity to ask for data (parameter)
5. format to save?  csv.....probably dataframe?

i'm starting to get a little worried.  this......could be upwards of.....oh boy....10 options now?  oh heck......at my day job, i would argue we should accept all of these as a parameters file, because this can get "big ugly fast".  and i don't know if a parameters file would be easier to pass around/keep track of.

**Comment by jamesfulford** [comment]
I think we need a better picture of how the pieces fit together, then we
can talk about what the interfaces (options, formats, etc.) ought to be. I
have some thoughts, but this PR is mainly expressing the logic of a
symphony.

**Comment by jamesfulford** [comment]
I thought about this some. I've updated the PR description to describe what part of the process this is about, limiting the scope somewhat.

**Comment by jamesfulford** [comment]
I did the hard work of comparing against the allocations Composer comes up with and am now at a point where every indicator appears to match (allowing for data source noise) and TQQQ for the long term allocations appear to match.

**Comment by jamesfulford** [comment]
backtest.py is not intended to stick around forever, I just needed a place to work. It'll be reorganized, but this PR is big enough as it is.

**Review by androslee — APPROVED** [review]

**Pull request merged**
